preload = $HOME/wallpapers/background.jpg
wallpaper = ,$HOME/wallpapers/background.jpg

exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = hyprpaper

# --- Keybindings ---
bind = SUPER, D, exec, fuzzel